"""meal planner enhancement

Revision ID: 85836d848be0
Revises: aa1ccb3cd4ed
Create Date: 2026-07-30 04:26:54.846299+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '85836d848be0'
down_revision: Union[str, None] = 'aa1ccb3cd4ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meal_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meal_plan_id', sa.Integer(), nullable=False),
    sa.Column('meal_type', sa.String(length=50), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('meal_name', sa.String(length=150), nullable=False),
    sa.Column('ingredients', sa.JSON(), nullable=True),
    sa.Column('nutrition', sa.JSON(), nullable=True),
    sa.Column('cooking_time', sa.Integer(), nullable=True),
    sa.Column('difficulty', sa.String(length=50), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['meal_plan_id'], ['meal_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_items_id'), 'meal_items', ['id'], unique=False)
    op.add_column('meal_plans', sa.Column('date', sa.Date(), nullable=False))
    op.add_column('meal_plans', sa.Column('breakfast', sa.JSON(), nullable=True))
    op.add_column('meal_plans', sa.Column('lunch', sa.JSON(), nullable=True))
    op.add_column('meal_plans', sa.Column('snack', sa.JSON(), nullable=True))
    op.add_column('meal_plans', sa.Column('dinner', sa.JSON(), nullable=True))
    op.add_column('meal_plans', sa.Column('total_calories', sa.Float(), nullable=True))
    op.add_column('meal_plans', sa.Column('total_protein', sa.Float(), nullable=True))
    op.add_column('meal_plans', sa.Column('total_carbs', sa.Float(), nullable=True))
    op.add_column('meal_plans', sa.Column('total_fats', sa.Float(), nullable=True))
    op.add_column('meal_plans', sa.Column('status', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_meal_plans_date'), 'meal_plans', ['date'], unique=False)
    op.drop_column('meal_plans', 'start_date')
    op.drop_column('meal_plans', 'meal_type')
    op.drop_column('meal_plans', 'calories')
    op.drop_column('meal_plans', 'meals')
    op.drop_column('meal_plans', 'name')
    op.drop_column('meal_plans', 'end_date')
    op.drop_column('meal_plans', 'plan_date')
    op.drop_column('meal_plans', 'recipe_name')
    op.drop_column('meal_plans', 'notes')
    op.add_column('settings', sa.Column('health_goal', sa.String(length=50), nullable=True))
    op.add_column('settings', sa.Column('cuisine_preferences', sa.JSON(), nullable=True))
    op.add_column('settings', sa.Column('disliked_foods', sa.JSON(), nullable=True))
    op.add_column('settings', sa.Column('cooking_time_preference', sa.Integer(), nullable=True))
    op.drop_constraint('users_google_id_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.create_unique_constraint('users_google_id_key', 'users', ['google_id'])
    op.drop_column('settings', 'cooking_time_preference')
    op.drop_column('settings', 'disliked_foods')
    op.drop_column('settings', 'cuisine_preferences')
    op.drop_column('settings', 'health_goal')
    op.add_column('meal_plans', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('meal_plans', sa.Column('recipe_name', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.add_column('meal_plans', sa.Column('plan_date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('meal_plans', sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('meal_plans', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('meal_plans', sa.Column('meals', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('meal_plans', sa.Column('calories', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('meal_plans', sa.Column('meal_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('meal_plans', sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_meal_plans_date'), table_name='meal_plans')
    op.drop_column('meal_plans', 'status')
    op.drop_column('meal_plans', 'total_fats')
    op.drop_column('meal_plans', 'total_carbs')
    op.drop_column('meal_plans', 'total_protein')
    op.drop_column('meal_plans', 'total_calories')
    op.drop_column('meal_plans', 'dinner')
    op.drop_column('meal_plans', 'snack')
    op.drop_column('meal_plans', 'lunch')
    op.drop_column('meal_plans', 'breakfast')
    op.drop_column('meal_plans', 'date')
    op.drop_index(op.f('ix_meal_items_id'), table_name='meal_items')
    op.drop_table('meal_items')
    # ### end Alembic commands ###
